steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - function-ingest2
      - --region=us-west2
      - --source=.
      - --trigger-http
      - --runtime=python38
      - --memory=1GB
      - --timeout=540
      - --min-instances=0
      - --max-instances=3000
      - --security-level=secure-always
      - --ingress-settings=all
      - --no-allow-unauthenticated
      - --service-account=warren-says@appspot.gserviceaccount.com
